language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: f41VJ5kvkFRoe+1XqZ383RPgkY4hiV85Q1cOJUpfEE9GyBu/6aKenNfu3RBBOTXeurohYMYI8YVHRgnZv/vGJvPow5DtXRLuP/iR+QKf4eWpv43DV8Ji512rBs2YYXsqL5EY9cXpifCBr7doEa9qMwcvZs4Zne6W8MVCCCKgtJ+AlxzdQwnk+lMFn/CWF3f+AdKVDiDBuq1mhfBHgHVkQ0TigwO7eGu+ACK49nhKWzNgF15q0VJ1u91Bh3+lCtIJHoAdVQ4ans7GZQPpifZ+6ImA9oM0CYIPdXrYPDZc30ENmRV1sgJGm75AhU0y70Ayq5x8Pac6bZ3iSlP/i3iyCqnJHaGdjoDmCDXageQNc13qWxoJm0QuT01WXrkBieNWzR44EzsjJ8MLEvEfLq5jWqPBtX36lsVQqelctH6+MHFnf7EhWuSELeF0bprbXwpzD36T8g4ovJL9of4I49yHkkbX2wuOwVtumVo0qStFZDk7pPvPqGuOL/pP7uoxrB1Sv+cglhJbe/17ZYZEaz1FQ+2QmUD5cKaVPKdxJYWErn+QzQ29mbW5+IQaZWnJypXPjx7GNobLz3YPb4qONGs2WwUNApMcWEsb6jkmpSNlcnKGEGNPde8dqw2iDIiSre6RzX2OLyGAp8fvWw8MsImjdqiQTDHPxl3Ab+s5GM7OMq4=
